services:
  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    volumes:
      - ..:/app
      - mix_deps:/app/deps
      - mix_build:/app/_build
      - mix_cache:/root/.mix
    working_dir: /app
    stdin_open: true
    tty: true
    environment:
      MIX_ENV: test
    networks:
      - dspace

volumes:
  mix_deps:
  mix_build:
  mix_cache:

networks:
  dspace:
